// <auto-generated />
using System;
using EmployeeManagement.Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeManagement.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230725012314_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeManagement.Shared.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CountryId = 1,
                            Name = "Afghanistan"
                        },
                        new
                        {
                            CountryId = 2,
                            Name = "Albania"
                        },
                        new
                        {
                            CountryId = 3,
                            Name = "Algeria"
                        },
                        new
                        {
                            CountryId = 4,
                            Name = "Andorra"
                        },
                        new
                        {
                            CountryId = 5,
                            Name = "Angola"
                        },
                        new
                        {
                            CountryId = 6,
                            Name = "Antigua and Barbuda"
                        },
                        new
                        {
                            CountryId = 7,
                            Name = "Argentina"
                        },
                        new
                        {
                            CountryId = 8,
                            Name = "Armenia"
                        },
                        new
                        {
                            CountryId = 9,
                            Name = "Australia"
                        },
                        new
                        {
                            CountryId = 10,
                            Name = "Austria"
                        },
                        new
                        {
                            CountryId = 11,
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            CountryId = 12,
                            Name = "Bahamas"
                        },
                        new
                        {
                            CountryId = 13,
                            Name = "Bahrain"
                        },
                        new
                        {
                            CountryId = 14,
                            Name = "Bangladesh"
                        },
                        new
                        {
                            CountryId = 15,
                            Name = "Barbados"
                        },
                        new
                        {
                            CountryId = 16,
                            Name = "Belarus"
                        },
                        new
                        {
                            CountryId = 17,
                            Name = "Belgium"
                        },
                        new
                        {
                            CountryId = 18,
                            Name = "Belize"
                        },
                        new
                        {
                            CountryId = 19,
                            Name = "Benin"
                        },
                        new
                        {
                            CountryId = 20,
                            Name = "Bhutan"
                        },
                        new
                        {
                            CountryId = 21,
                            Name = "Bolivia"
                        },
                        new
                        {
                            CountryId = 22,
                            Name = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            CountryId = 23,
                            Name = "Botswana"
                        },
                        new
                        {
                            CountryId = 24,
                            Name = "Brazil"
                        },
                        new
                        {
                            CountryId = 25,
                            Name = "Brunei"
                        },
                        new
                        {
                            CountryId = 26,
                            Name = "Bulgaria"
                        },
                        new
                        {
                            CountryId = 27,
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            CountryId = 28,
                            Name = "Burundi"
                        },
                        new
                        {
                            CountryId = 29,
                            Name = "Cabo Verde"
                        },
                        new
                        {
                            CountryId = 30,
                            Name = "Cambodia"
                        },
                        new
                        {
                            CountryId = 31,
                            Name = "Cameroon"
                        },
                        new
                        {
                            CountryId = 32,
                            Name = "Canada"
                        },
                        new
                        {
                            CountryId = 33,
                            Name = "Central African Republic"
                        },
                        new
                        {
                            CountryId = 34,
                            Name = "Chad"
                        },
                        new
                        {
                            CountryId = 35,
                            Name = "Chile"
                        },
                        new
                        {
                            CountryId = 36,
                            Name = "China"
                        },
                        new
                        {
                            CountryId = 37,
                            Name = "Colombia"
                        },
                        new
                        {
                            CountryId = 38,
                            Name = "Comoros"
                        },
                        new
                        {
                            CountryId = 39,
                            Name = "Congo"
                        },
                        new
                        {
                            CountryId = 40,
                            Name = "Costa Rica"
                        },
                        new
                        {
                            CountryId = 41,
                            Name = "Croatia"
                        },
                        new
                        {
                            CountryId = 42,
                            Name = "Cuba"
                        },
                        new
                        {
                            CountryId = 43,
                            Name = "Cyprus"
                        },
                        new
                        {
                            CountryId = 44,
                            Name = "Czechia"
                        },
                        new
                        {
                            CountryId = 45,
                            Name = "Denmark"
                        },
                        new
                        {
                            CountryId = 46,
                            Name = "Djibouti"
                        },
                        new
                        {
                            CountryId = 47,
                            Name = "Dominica"
                        },
                        new
                        {
                            CountryId = 48,
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            CountryId = 49,
                            Name = "Ecuador"
                        },
                        new
                        {
                            CountryId = 50,
                            Name = "Egypt"
                        },
                        new
                        {
                            CountryId = 51,
                            Name = "El Salvador"
                        },
                        new
                        {
                            CountryId = 52,
                            Name = "Equatorial Guinea"
                        },
                        new
                        {
                            CountryId = 53,
                            Name = "Eritrea"
                        },
                        new
                        {
                            CountryId = 54,
                            Name = "Estonia"
                        },
                        new
                        {
                            CountryId = 55,
                            Name = "Eswatini"
                        },
                        new
                        {
                            CountryId = 56,
                            Name = "Ethiopia"
                        },
                        new
                        {
                            CountryId = 57,
                            Name = "Fiji"
                        },
                        new
                        {
                            CountryId = 58,
                            Name = "Finland"
                        },
                        new
                        {
                            CountryId = 59,
                            Name = "France"
                        },
                        new
                        {
                            CountryId = 60,
                            Name = "Gabon"
                        },
                        new
                        {
                            CountryId = 61,
                            Name = "Gambia"
                        },
                        new
                        {
                            CountryId = 62,
                            Name = "Georgia"
                        },
                        new
                        {
                            CountryId = 63,
                            Name = "Germany"
                        },
                        new
                        {
                            CountryId = 64,
                            Name = "Ghana"
                        },
                        new
                        {
                            CountryId = 65,
                            Name = "Greece"
                        },
                        new
                        {
                            CountryId = 66,
                            Name = "Grenada"
                        },
                        new
                        {
                            CountryId = 67,
                            Name = "Guatemala"
                        },
                        new
                        {
                            CountryId = 68,
                            Name = "Guinea"
                        },
                        new
                        {
                            CountryId = 69,
                            Name = "Guinea-Bissau"
                        },
                        new
                        {
                            CountryId = 70,
                            Name = "Guyana"
                        },
                        new
                        {
                            CountryId = 71,
                            Name = "Haiti"
                        },
                        new
                        {
                            CountryId = 72,
                            Name = "Honduras"
                        },
                        new
                        {
                            CountryId = 73,
                            Name = "Hungary"
                        },
                        new
                        {
                            CountryId = 74,
                            Name = "Iceland"
                        },
                        new
                        {
                            CountryId = 75,
                            Name = "India"
                        },
                        new
                        {
                            CountryId = 76,
                            Name = "Indonesia"
                        },
                        new
                        {
                            CountryId = 77,
                            Name = "Iran"
                        },
                        new
                        {
                            CountryId = 78,
                            Name = "Iraq"
                        },
                        new
                        {
                            CountryId = 79,
                            Name = "Ireland"
                        },
                        new
                        {
                            CountryId = 80,
                            Name = "Israel"
                        },
                        new
                        {
                            CountryId = 81,
                            Name = "Italy"
                        },
                        new
                        {
                            CountryId = 82,
                            Name = "Jamaica"
                        },
                        new
                        {
                            CountryId = 83,
                            Name = "Japan"
                        },
                        new
                        {
                            CountryId = 84,
                            Name = "Jordan"
                        },
                        new
                        {
                            CountryId = 85,
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            CountryId = 86,
                            Name = "Kenya"
                        },
                        new
                        {
                            CountryId = 87,
                            Name = "Kiribati"
                        },
                        new
                        {
                            CountryId = 88,
                            Name = "Korea, North"
                        },
                        new
                        {
                            CountryId = 89,
                            Name = "Korea, South"
                        },
                        new
                        {
                            CountryId = 90,
                            Name = "Kosovo"
                        },
                        new
                        {
                            CountryId = 91,
                            Name = "Kuwait"
                        },
                        new
                        {
                            CountryId = 92,
                            Name = "Kyrgyzstan"
                        },
                        new
                        {
                            CountryId = 93,
                            Name = "Laos"
                        },
                        new
                        {
                            CountryId = 94,
                            Name = "Latvia"
                        },
                        new
                        {
                            CountryId = 95,
                            Name = "Lebanon"
                        },
                        new
                        {
                            CountryId = 96,
                            Name = "Lesotho"
                        },
                        new
                        {
                            CountryId = 97,
                            Name = "Liberia"
                        },
                        new
                        {
                            CountryId = 98,
                            Name = "Libya"
                        },
                        new
                        {
                            CountryId = 99,
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            CountryId = 100,
                            Name = "Lithuania"
                        },
                        new
                        {
                            CountryId = 101,
                            Name = "Luxembourg"
                        },
                        new
                        {
                            CountryId = 102,
                            Name = "Madagascar"
                        },
                        new
                        {
                            CountryId = 103,
                            Name = "Malawi"
                        },
                        new
                        {
                            CountryId = 104,
                            Name = "Malaysia"
                        },
                        new
                        {
                            CountryId = 105,
                            Name = "Maldives"
                        },
                        new
                        {
                            CountryId = 106,
                            Name = "Mali"
                        },
                        new
                        {
                            CountryId = 107,
                            Name = "Malta"
                        },
                        new
                        {
                            CountryId = 108,
                            Name = "Marshall Islands"
                        },
                        new
                        {
                            CountryId = 109,
                            Name = "Mauritania"
                        },
                        new
                        {
                            CountryId = 110,
                            Name = "Mauritius"
                        },
                        new
                        {
                            CountryId = 111,
                            Name = "Mexico"
                        },
                        new
                        {
                            CountryId = 112,
                            Name = "Micronesia"
                        },
                        new
                        {
                            CountryId = 113,
                            Name = "Moldova"
                        },
                        new
                        {
                            CountryId = 114,
                            Name = "Monaco"
                        },
                        new
                        {
                            CountryId = 115,
                            Name = "Mongolia"
                        },
                        new
                        {
                            CountryId = 116,
                            Name = "Montenegro"
                        },
                        new
                        {
                            CountryId = 117,
                            Name = "Morocco"
                        },
                        new
                        {
                            CountryId = 118,
                            Name = "Mozambique"
                        },
                        new
                        {
                            CountryId = 119,
                            Name = "Myanmar"
                        },
                        new
                        {
                            CountryId = 120,
                            Name = "Namibia"
                        },
                        new
                        {
                            CountryId = 121,
                            Name = "Nauru"
                        },
                        new
                        {
                            CountryId = 122,
                            Name = "Nepal"
                        },
                        new
                        {
                            CountryId = 123,
                            Name = "Netherlands"
                        },
                        new
                        {
                            CountryId = 124,
                            Name = "New Zealand"
                        },
                        new
                        {
                            CountryId = 125,
                            Name = "Nicaragua"
                        },
                        new
                        {
                            CountryId = 126,
                            Name = "Niger"
                        },
                        new
                        {
                            CountryId = 127,
                            Name = "Nigeria"
                        },
                        new
                        {
                            CountryId = 128,
                            Name = "North Macedonia"
                        },
                        new
                        {
                            CountryId = 129,
                            Name = "Norway"
                        },
                        new
                        {
                            CountryId = 130,
                            Name = "Oman"
                        },
                        new
                        {
                            CountryId = 131,
                            Name = "Pakistan"
                        },
                        new
                        {
                            CountryId = 132,
                            Name = "Palau"
                        },
                        new
                        {
                            CountryId = 133,
                            Name = "Panama"
                        },
                        new
                        {
                            CountryId = 134,
                            Name = "Papua New Guinea"
                        },
                        new
                        {
                            CountryId = 135,
                            Name = "Paraguay"
                        },
                        new
                        {
                            CountryId = 136,
                            Name = "Peru"
                        },
                        new
                        {
                            CountryId = 137,
                            Name = "Philippines"
                        },
                        new
                        {
                            CountryId = 138,
                            Name = "Poland"
                        },
                        new
                        {
                            CountryId = 139,
                            Name = "Portugal"
                        },
                        new
                        {
                            CountryId = 140,
                            Name = "Qatar"
                        },
                        new
                        {
                            CountryId = 141,
                            Name = "Romania"
                        },
                        new
                        {
                            CountryId = 142,
                            Name = "Russia"
                        },
                        new
                        {
                            CountryId = 143,
                            Name = "Rwanda"
                        },
                        new
                        {
                            CountryId = 144,
                            Name = "Saint Kitts and Nevis"
                        },
                        new
                        {
                            CountryId = 145,
                            Name = "Saint Lucia"
                        },
                        new
                        {
                            CountryId = 146,
                            Name = "Saint Vincent and the Grenadines"
                        },
                        new
                        {
                            CountryId = 147,
                            Name = "Samoa"
                        },
                        new
                        {
                            CountryId = 148,
                            Name = "San Marino"
                        },
                        new
                        {
                            CountryId = 149,
                            Name = "Sao Tome and Principe"
                        },
                        new
                        {
                            CountryId = 150,
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            CountryId = 151,
                            Name = "Senegal"
                        },
                        new
                        {
                            CountryId = 152,
                            Name = "Serbia"
                        },
                        new
                        {
                            CountryId = 153,
                            Name = "Seychelles"
                        },
                        new
                        {
                            CountryId = 154,
                            Name = "Sierra Leone"
                        },
                        new
                        {
                            CountryId = 155,
                            Name = "Singapore"
                        },
                        new
                        {
                            CountryId = 156,
                            Name = "Slovakia"
                        },
                        new
                        {
                            CountryId = 157,
                            Name = "Slovenia"
                        },
                        new
                        {
                            CountryId = 158,
                            Name = "Solomon Islands"
                        },
                        new
                        {
                            CountryId = 159,
                            Name = "Somalia"
                        },
                        new
                        {
                            CountryId = 160,
                            Name = "South Africa"
                        },
                        new
                        {
                            CountryId = 161,
                            Name = "South Sudan"
                        },
                        new
                        {
                            CountryId = 162,
                            Name = "Spain"
                        },
                        new
                        {
                            CountryId = 163,
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            CountryId = 164,
                            Name = "Sudan"
                        },
                        new
                        {
                            CountryId = 165,
                            Name = "Suriname"
                        },
                        new
                        {
                            CountryId = 166,
                            Name = "Sweden"
                        },
                        new
                        {
                            CountryId = 167,
                            Name = "Switzerland"
                        },
                        new
                        {
                            CountryId = 168,
                            Name = "Syria"
                        },
                        new
                        {
                            CountryId = 169,
                            Name = "Taiwan"
                        },
                        new
                        {
                            CountryId = 170,
                            Name = "Tajikistan"
                        },
                        new
                        {
                            CountryId = 171,
                            Name = "Tanzania"
                        },
                        new
                        {
                            CountryId = 172,
                            Name = "Thailand"
                        },
                        new
                        {
                            CountryId = 173,
                            Name = "Timor-Leste"
                        },
                        new
                        {
                            CountryId = 174,
                            Name = "Togo"
                        },
                        new
                        {
                            CountryId = 175,
                            Name = "Tonga"
                        },
                        new
                        {
                            CountryId = 176,
                            Name = "Trinidad and Tobago"
                        },
                        new
                        {
                            CountryId = 177,
                            Name = "Tunisia"
                        },
                        new
                        {
                            CountryId = 178,
                            Name = "Turkey"
                        },
                        new
                        {
                            CountryId = 179,
                            Name = "Turkmenistan"
                        },
                        new
                        {
                            CountryId = 180,
                            Name = "Tuvalu"
                        },
                        new
                        {
                            CountryId = 181,
                            Name = "Uganda"
                        },
                        new
                        {
                            CountryId = 182,
                            Name = "Ukraine"
                        },
                        new
                        {
                            CountryId = 183,
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            CountryId = 184,
                            Name = "United Kingdom"
                        },
                        new
                        {
                            CountryId = 185,
                            Name = "United States of America"
                        },
                        new
                        {
                            CountryId = 186,
                            Name = "Uruguay"
                        },
                        new
                        {
                            CountryId = 187,
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            CountryId = 188,
                            Name = "Vanuatu"
                        },
                        new
                        {
                            CountryId = 189,
                            Name = "Vatican City"
                        },
                        new
                        {
                            CountryId = 190,
                            Name = "Venezuela"
                        },
                        new
                        {
                            CountryId = 191,
                            Name = "Vietnam"
                        },
                        new
                        {
                            CountryId = 192,
                            Name = "Yemen"
                        },
                        new
                        {
                            CountryId = 193,
                            Name = "Zambia"
                        },
                        new
                        {
                            CountryId = 194,
                            Name = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("EmployeeManagement.Shared.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExitDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<int>("JobCategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("JoinedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MaritalStatus")
                        .HasColumnType("int");

                    b.Property<int>("OfficeId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("OfficeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            BirthDate = new DateTime(1984, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Atlanta",
                            Comment = "Lorem Ipsum",
                            CountryId = 185,
                            Email = "emily@gmail.com",
                            FirstName = "Emily",
                            Gender = 1,
                            JobCategoryId = 7,
                            JoinedDate = new DateTime(2020, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Davis",
                            MaritalStatus = 1,
                            OfficeId = 2,
                            PhoneNumber = "33669933221",
                            Street = "Piedmont Avenue",
                            Zip = "30305"
                        },
                        new
                        {
                            EmployeeId = 2,
                            BirthDate = new DateTime(1988, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "London",
                            Comment = "Lorem Ipsum",
                            CountryId = 184,
                            Email = "michael@gmail.com",
                            FirstName = "Michael",
                            Gender = 0,
                            JobCategoryId = 8,
                            JoinedDate = new DateTime(2019, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Wilson",
                            MaritalStatus = 0,
                            OfficeId = 3,
                            PhoneNumber = "77665544331",
                            Street = "Baker Street",
                            Zip = "SW1X 7XL"
                        },
                        new
                        {
                            EmployeeId = 3,
                            BirthDate = new DateTime(1985, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "New York",
                            Comment = "Lorem Ipsum",
                            CountryId = 185,
                            Email = "john@gmail.com",
                            FirstName = "John",
                            Gender = 2,
                            JobCategoryId = 2,
                            JoinedDate = new DateTime(2020, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Doe",
                            MaritalStatus = 1,
                            OfficeId = 1,
                            PhoneNumber = "33888809823",
                            Street = "Broadway",
                            Zip = "10001"
                        },
                        new
                        {
                            EmployeeId = 4,
                            BirthDate = new DateTime(1990, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Atlanta",
                            Comment = "Lorem Ipsum",
                            CountryId = 185,
                            Email = "jane@gmail.com",
                            FirstName = "Jane",
                            Gender = 1,
                            JobCategoryId = 3,
                            JoinedDate = new DateTime(2019, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Doe",
                            MaritalStatus = 0,
                            OfficeId = 2,
                            PhoneNumber = "33777709823",
                            Street = "Peachtree Street",
                            Zip = "30303"
                        },
                        new
                        {
                            EmployeeId = 5,
                            BirthDate = new DateTime(1982, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "London",
                            Comment = "Lorem Ipsum",
                            CountryId = 184,
                            Email = "sarah@gmail.com",
                            FirstName = "Sarah",
                            Gender = 1,
                            JobCategoryId = 4,
                            JoinedDate = new DateTime(2018, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Johnson",
                            MaritalStatus = 1,
                            OfficeId = 3,
                            PhoneNumber = "44332210987",
                            Street = "Oxford Street",
                            Zip = "SW1A 1AA"
                        },
                        new
                        {
                            EmployeeId = 6,
                            BirthDate = new DateTime(1981, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Lisbon",
                            Comment = "Lorem Ipsum",
                            CountryId = 139,
                            Email = "peter@gmail.com",
                            FirstName = "Peter",
                            Gender = 0,
                            JobCategoryId = 5,
                            JoinedDate = new DateTime(2017, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Miller",
                            MaritalStatus = 1,
                            OfficeId = 4,
                            PhoneNumber = "55443322119",
                            Street = "Rua Augusta",
                            Zip = "1100"
                        },
                        new
                        {
                            EmployeeId = 7,
                            BirthDate = new DateTime(1992, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "New York",
                            Comment = "Lorem Ipsum",
                            CountryId = 185,
                            Email = "david@gmail.com",
                            FirstName = "David",
                            Gender = 2,
                            JobCategoryId = 6,
                            JoinedDate = new DateTime(2022, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Brown",
                            MaritalStatus = 0,
                            OfficeId = 1,
                            PhoneNumber = "33221199008",
                            Street = "5th Avenue",
                            Zip = "10018"
                        },
                        new
                        {
                            EmployeeId = 8,
                            BirthDate = new DateTime(1989, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Los Angeles",
                            Comment = "Lorem Ipsum",
                            CountryId = 185,
                            Email = "alex@gmail.com",
                            FirstName = "Alex",
                            Gender = 0,
                            JobCategoryId = 7,
                            JoinedDate = new DateTime(2021, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Robinson",
                            MaritalStatus = 1,
                            OfficeId = 5,
                            PhoneNumber = "55443322119",
                            Street = "Sunset Boulevard",
                            Zip = "90028"
                        },
                        new
                        {
                            EmployeeId = 9,
                            BirthDate = new DateTime(1991, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Toronto",
                            Comment = "Lorem Ipsum",
                            CountryId = 32,
                            Email = "natalie@gmail.com",
                            FirstName = "Natalie",
                            Gender = 1,
                            JobCategoryId = 8,
                            JoinedDate = new DateTime(2021, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Lee",
                            MaritalStatus = 1,
                            OfficeId = 5,
                            PhoneNumber = "33445566778",
                            Street = "Yonge Street",
                            Zip = "M5E 1W7"
                        },
                        new
                        {
                            EmployeeId = 10,
                            BirthDate = new DateTime(1987, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Tokyo",
                            Comment = "Lorem Ipsum",
                            CountryId = 83,
                            Email = "hiroshi@gmail.com",
                            FirstName = "Hiroshi",
                            Gender = 0,
                            JobCategoryId = 9,
                            JoinedDate = new DateTime(2021, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Tanaka",
                            MaritalStatus = 1,
                            OfficeId = 5,
                            PhoneNumber = "33887766442",
                            Street = "Ginza Street",
                            Zip = "104-0061"
                        },
                        new
                        {
                            EmployeeId = 11,
                            BirthDate = new DateTime(1983, 11, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Sydney",
                            Comment = "Lorem Ipsum",
                            CountryId = 9,
                            Email = "sophie@gmail.com",
                            FirstName = "Sophie",
                            Gender = 1,
                            JobCategoryId = 7,
                            JoinedDate = new DateTime(2021, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Williams",
                            MaritalStatus = 0,
                            OfficeId = 5,
                            PhoneNumber = "44665533442",
                            Street = "George Street",
                            Zip = "2000"
                        },
                        new
                        {
                            EmployeeId = 12,
                            BirthDate = new DateTime(1986, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Paris",
                            Comment = "Lorem Ipsum",
                            CountryId = 59,
                            Email = "luc@gmail.com",
                            FirstName = "Luc",
                            Gender = 0,
                            JobCategoryId = 6,
                            JoinedDate = new DateTime(2021, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Martin",
                            MaritalStatus = 1,
                            OfficeId = 5,
                            PhoneNumber = "33998877665",
                            Street = "Champs-Élysées",
                            Zip = "75008"
                        },
                        new
                        {
                            EmployeeId = 13,
                            BirthDate = new DateTime(1980, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Berlin",
                            Comment = "Lorem Ipsum",
                            CountryId = 63,
                            Email = "anna@gmail.com",
                            FirstName = "Anna",
                            Gender = 1,
                            JobCategoryId = 8,
                            JoinedDate = new DateTime(2021, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Schmidt",
                            MaritalStatus = 0,
                            OfficeId = 5,
                            PhoneNumber = "33557799001",
                            Street = "Unter den Linden",
                            Zip = "10117"
                        },
                        new
                        {
                            EmployeeId = 14,
                            BirthDate = new DateTime(1989, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Dubai",
                            Comment = "Lorem Ipsum",
                            CountryId = 183,
                            Email = "ali@gmail.com",
                            FirstName = "Ali",
                            Gender = 0,
                            JobCategoryId = 9,
                            JoinedDate = new DateTime(2021, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Khan",
                            MaritalStatus = 1,
                            OfficeId = 5,
                            PhoneNumber = "55443366221",
                            Street = "Sheikh Zayed Road",
                            Zip = "Dubai"
                        },
                        new
                        {
                            EmployeeId = 15,
                            BirthDate = new DateTime(1992, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Moscow",
                            Comment = "Lorem Ipsum",
                            CountryId = 142,
                            Email = "igor@gmail.com",
                            FirstName = "Igor",
                            Gender = 0,
                            JobCategoryId = 7,
                            JoinedDate = new DateTime(2021, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Sokolov",
                            MaritalStatus = 0,
                            OfficeId = 5,
                            PhoneNumber = "33221177888",
                            Street = "Tverskaya Street",
                            Zip = "125009"
                        });
                });

            modelBuilder.Entity("EmployeeManagement.Shared.JobCategory", b =>
                {
                    b.Property<int>("JobCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobCategoryId"));

                    b.Property<string>("JobCategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JobCategoryId");

                    b.ToTable("JobCategories");

                    b.HasData(
                        new
                        {
                            JobCategoryId = 1,
                            JobCategoryName = "IT"
                        },
                        new
                        {
                            JobCategoryId = 2,
                            JobCategoryName = "Administration"
                        },
                        new
                        {
                            JobCategoryId = 3,
                            JobCategoryName = "Finance"
                        },
                        new
                        {
                            JobCategoryId = 4,
                            JobCategoryName = "Human Resources"
                        },
                        new
                        {
                            JobCategoryId = 5,
                            JobCategoryName = "Sales"
                        },
                        new
                        {
                            JobCategoryId = 6,
                            JobCategoryName = "Marketing"
                        },
                        new
                        {
                            JobCategoryId = 7,
                            JobCategoryName = "Quality Assurance"
                        },
                        new
                        {
                            JobCategoryId = 8,
                            JobCategoryName = "Project Management"
                        },
                        new
                        {
                            JobCategoryId = 9,
                            JobCategoryName = "Customer Support"
                        },
                        new
                        {
                            JobCategoryId = 10,
                            JobCategoryName = "Facilities Management"
                        },
                        new
                        {
                            JobCategoryId = 11,
                            JobCategoryName = "Security"
                        },
                        new
                        {
                            JobCategoryId = 12,
                            JobCategoryName = "Data Science"
                        });
                });

            modelBuilder.Entity("EmployeeManagement.Shared.Office", b =>
                {
                    b.Property<int>("OfficeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OfficeId"));

                    b.Property<double>("OfficeLatitude")
                        .HasColumnType("float");

                    b.Property<double>("OfficeLongitude")
                        .HasColumnType("float");

                    b.Property<string>("OfficeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OfficeId");

                    b.ToTable("Offices");

                    b.HasData(
                        new
                        {
                            OfficeId = 1,
                            OfficeLatitude = 40.748389143217913,
                            OfficeLongitude = -73.985921912007811,
                            OfficeName = "Company Headquarters - New York"
                        },
                        new
                        {
                            OfficeId = 2,
                            OfficeLatitude = 33.736252666893208,
                            OfficeLongitude = -84.409577686448841,
                            OfficeName = "Office 1 - Atlanta"
                        },
                        new
                        {
                            OfficeId = 3,
                            OfficeLatitude = 51.508111031504846,
                            OfficeLongitude = -0.12336713332934048,
                            OfficeName = "Office 2 - London"
                        },
                        new
                        {
                            OfficeId = 4,
                            OfficeLatitude = 38.742361381016686,
                            OfficeLongitude = -9.1452582659131956,
                            OfficeName = "Office 4 - Lisbon"
                        },
                        new
                        {
                            OfficeId = 5,
                            OfficeLatitude = 40.0,
                            OfficeLongitude = -40.0,
                            OfficeName = "Remote Office"
                        });
                });

            modelBuilder.Entity("EmployeeManagement.Shared.Employee", b =>
                {
                    b.HasOne("EmployeeManagement.Shared.Office", "Office")
                        .WithMany()
                        .HasForeignKey("OfficeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Office");
                });
#pragma warning restore 612, 618
        }
    }
}
